DROP INDEX neza4283.Automobiliui;
DROP INDEX neza4283.Filtrui;
DROP TRIGGER MinFiltruSkaicius ON neza4283.FiltroTaikomumas;
DROP FUNCTION KiekioTikrinimas();
DROP TRIGGER MinFiltruSkaicius2 ON neza4283.FiltroTaikomumas;
DROP FUNCTION KiekioTikrinimas2();
DROP VIEW	Filtrai;
DROP VIEW  	KokybiskiFiltrai;
DROP VIEW 	FiltraiPagalKategorija;
DROP TABLE FiltroTaikomumas;
DROP TABLE Filtras;
DROP TABLE Automobilis;
DROP TABLE Gamintojas;
